### ISSUE TITLE
Course exercises no longer being shown as completed?

### ISSUE THREAD

**Issue by benjs2000** [rage/tmc-vscode#264] opened 2020-03-20 12:37 UTC
Hi, After downloading Part 2 of the Java I MOOC, the exercises still have an red cross next to them even after they have been successfully submitted to the server.

They show up as complete on https://tmc.mooc.fi/ but not in the TMC menu?

This issue did not occur for the part 1 exercises?

Thanks

**Comment by jesseanttila-cai** [comment] 2020-03-20 14:02
Hi,

This issue is likely to be caused by a delay in exercise completion data propagation on the TMC server, which is currently being investigated by a different team.

The plugin currently fetches the completion data from the server whenever the exercise download view is opened, so you'll have to do that to get the latest data at the moment. The exercises should show as completed within an hour of a successful submission, as long as you've fetched the latest data by opening the downloads view.

Note that the exercises will also be locally marked as completed upon successful submission, but it will be overwritten by information received from the server.

**Comment by sebazai** [comment] 2020-03-30 10:51
Hi @benjs2000 

We have released version 0.2.0. 
Could you please verify if this issue has been resolved with the new version release.

**Closed** 2020-03-30 13:03 UTC
